apiVersion: v1
kind: Service
metadata:
  name: azure-keyvault-service
  namespace: poc-uat
spec:
  selector:
    app: azure-keyvault-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
